"""empty message

Revision ID: 2c3c08a75e5d
Revises: aeb5545c3613
Create Date: 2021-07-29 05:05:44.894483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3c08a75e5d'
down_revision = 'aeb5545c3613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'image_link')
    # ### end Alembic commands ###
