"""empty message

Revision ID: 573890f68758
Revises: ba4845031f91
Create Date: 2021-06-17 06:14:37.999644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '573890f68758'
down_revision = 'ba4845031f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('past_shows', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.add_column('Artist', sa.Column('upcoming_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('past_shows', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
